spring:
  application:
    name: kotlin_test

  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:13306/mytest
        username: root
        password: password
    replica:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:13307/mytest
        username: root
        password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
---
spring:
  config:
    activate:
      on-profile: development
---
spring:
  config:
    activate:
      on-profile: production
